version: '3.3'

services:
   db:
      image: mysql:5.7
      volumes:
         - db_data:/var/lib/mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: Fourwordsalluppercase1
         MYSQL_DATABASE: taowp
         MYSQL_USER: taowp
         MYSQL_PASSWORD: Fourwordsalluppercase1

   wordpress:
      depends_on:
         - db
      image: wordpress:latest
      ports:
         - "8000:80"
      restart: always
      environment:
         WORDPRESS_DB_HOST: db:3306
         WORDPRESS_DB_USER: taowp
         WORDPRESS_DB_PASSWORD: Fourwordsalluppercase1
         WORDPRESS_DB_NAME: taowp
volumes:
   db_data: {}
